version: '3'

services:
  gemini:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - default
    depends_on:
      - db
  db:
      image: postgres:17-alpine
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: bot_db
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      networks:
        - default
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 10s
        retries: 5

networks:
  default:
    driver: bridge
