services:
    db:
      image: postgres:17-alpine
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: bot_db
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      networks:
        - default
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 5s
    gemini:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      volumes:
        - ./config.yml:/app/config.yml
      networks:
        - default
      depends_on:
        db:
          condition: service_healthy
networks:
  default:
    driver: bridge
